### PR TITLE
Navbar added

### PR DESCRIPTION
**Pull request by kushal7201**
Issue: #2

### CODE REVIEW

**Comment by 0mBudsMan** [comment]
@kushal7201 Implement necessary changes asap!!

**Comment by kushal7201** [comment]
@0mBudsMan Which changes to implement?

**Comment by kushal7201** [comment]
@0mBudsMan Please Reply

**Comment by 0mBudsMan** [comment]
@kushal7201 your navbar doesn't look like my figma design's navbar. Make that changes done

**Pull request closed without merging**
