### PR TITLE
Account Management

### PR DESCRIPTION
**Pull request by Karansenpai**
Issue: #81 

for account management page go to

http://localhost:3000/account

Screenshot from 2023-12-19 00-07-26
Screenshot from 2023-12-19 00-07-23
Screenshot from 2023-12-19 00-07-00

### CODE REVIEW

**Comment by 0mBudsMan** [comment]
@Karansenpai 
Accurate and perfect! Can you also fix responsiveness? The website is not fully responsive

**Comment by Karansenpai** [comment]
@0mBudsMan check now i have make the gap between div in mobile mode and tried to make the page more responsive

**Comment by 0mBudsMan** [comment]
@Karansenpai looks good! Can you make one more change? Whenever any text field is changed, please add a text saying "Name or Username is being changed" (use OnChange) in Account Details Section. Below it, add a submit button.

Also, add a prop disabled="true" in email address text field

**Comment by Karansenpai** [comment]
disabled = "true" always or when the user is changing username

**Comment by 0mBudsMan** [comment]
Awesome work, Karan! Just add a submit button when something is being edited, so that final edited profile can be saved to database.

**Comment by 0mBudsMan** [comment]
Awesome work! Just add custom success button from mui
Shift the content to the right as shown
Screenshot (365)

**Comment by Karansenpai** [comment]
@0mBudsMan edited check now

**Pull request merged**
