### PR TITLE
Footer component

### PR DESCRIPTION
**Pull request by Karansenpai**
Issue: #35 

Screenshot from 2023-12-17 02-50-16
Screenshot from 2023-12-17 02-50-33
Screenshot from 2023-12-17 02-50-40

### CODE REVIEW

**Comment by 0mBudsMan** [comment]
@Karansenpai 
Awesome going Karan! Just a minor fix! Check the font size, and if needed, display only top three categories, so that container does not necessarily look this big. Also, make sure you remove the bottom: 0 property, it is causing issues.
Kindly review this by tomorrow. Good luck
Screenshot (340)

**Comment by Karansenpai** [comment]
Ok sure, fixings these bugs

**Comment by Karansenpai** [comment]
@0mBudsMan check now 

Fixes the font size and fixes the padding Margin

**Comment by Karansenpai** [comment]
@0mBudsMan

**Pull request merged**
