### PR TITLE
bug fixed

### PR DESCRIPTION
**Pull request by TheDivineAurora**
Issue: #82 

fixed overflow

### CODE REVIEW

**Comment by 0mBudsMan** [comment]
@TheDivineAurora Can u send ss from ur device? This is how it looks like from my screen
Screenshot (368)

**Comment by TheDivineAurora** [comment]
image

**Comment by TheDivineAurora** [comment]
i ran in on vercel to verify too it was fine

**Comment by 0mBudsMan** [comment]
@TheDivineAurora please send vercel link

**Comment by TheDivineAurora** [comment]
https://scoop-frontend-ab1girrkl-thedivineaurora.vercel.app/

**Pull request closed without merging**
